### ISSUE TITLE
Tab sizes of HTML

### ISSUE THREAD

**Issue by laubonghaudoi** [cantonese-community/cantonese-community.github.io#1]
The HTMLs are currently formatted with spaces in size 4, which looks too spacious for dense contents like this. In addition, some parts of the htmls, e.g. the unordered lists and list items are not formatted / indented well. Can I reformat the files with Prettier? I prefer using space 2 indentation. @RuohanZhan @anbenson

**Comment by RuohanZhan** [comment]
please do!

**Comment by laubonghaudoi** [comment]
All pages are reformatted in fe0ec6cd083af0e48af4cd8ff6e2909d8625c2a3 , closing this issue
